### ISSUE TITLE
Green Tip Friday - July 26th Post

### ISSUE THREAD

**Issue by yigakpoa** [clentafrica/marketing-and-comms#10]
Happy Friday! 🌿 Here’s a green tip to kick off your weekend: Switch to energy-efficient bulbs, like LEDs or CFLs, to significantly reduce your carbon footprint. These bulbs use up to 80% less energy than traditional incandescent bulbs and last much longer, saving you money on your energy bill while helping the environment.

Remember, small changes in our daily habits can lead to big differences in our planet’s health. Let’s all do our part for a more sustainable and eco-friendly future!

#GreenTip #EnergyEfficiency #SustainableLiving #EcoFriendly #ClimateAction #SaveEnergy #GoGreen #CLENTAfrica #GreenPractices #ClimateChange #RenewableEnergy

**Comment by yigakpoa** [comment]
Is anyone from the @clentafrica/wg-design available to work on this for the marketing team? Please indicate here. Thank you.

**Comment by CharlesSodipo** [comment]
Sure, I can!

**Comment by yigakpoa** [comment]
Awesome @CharlesSodipo. I have just assigned you the task so you can work on it. 

When you’re done, please use @clentafrica/wg-marketing-comms to notify the marketing working group to view it. You can find our assets here:

**Comment by CharlesSodipo** [comment]
Alright
I have gone through the assets and I understand them, but I do not seem so find how to download the raw files, please do help. Thank you.
Also to be sure we are on the same page, I am creating a social media flier right?

**Comment by SDauphin15** [comment]
Good afternoon,

What was my assignment for today again? I lost the email for some reason.
Please let me know. Thank you.

Best,
Soraya

**Comment by SDauphin15** [comment]
Disregard I found it.

**Comment by yigakpoa** [comment]
@clentafrica/wg-design, please let me know what you think about this design, it’s meant to go out tomorrow.


![Image](https://github.com/user-attachments/assets/247d5f2e-697f-4e67-ad23-e4c3509083da)

**Comment by SDauphin15** [comment]
Looks great!

**Comment by chibuikemezesionwu** [comment]
> @clentafrica/wg-design, please let me know what you think about this design, it’s meant to go out tomorrow.
> 
> ![Image](https://private-user-images.githubusercontent.com/99066793/352291529-247d5f2e-697f-4e67-ad23-e4c3509083da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NDQxMTAsIm5iZiI6MTcyMTk0MzgxMCwicGF0aCI6Ii85OTA2Njc5My8zNTIyOTE1MjktMjQ3ZDVmMmUtNjk3Zi00ZTY3LWFkMjMtZTRjMzUwOTA4M2RhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDIxNDMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1MTg5YmZmNmMyZWUyYjBmYmFkNjRhNjFmYzZmZDNjOTRiYmY4MDhlNDgwOTZjNGRjZGU0YmEwMGI3YTcxNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ixBErRULpWX1rFF-tyOprvRENu1QgAgGINno8Iwa08k)

This is calm

**Comment by yigakpoa** [comment]
Awesome! Thank you team @SDauphin15 & @chibuikemezesionwu for the quick reviews 💃. 

Over to team social media @SDauphin15. Please can you designate your team mates against tomorrow 🥁

**Comment by SDauphin15** [comment]
Hey,

Designate the teammates regarding what exactly. Please let me know. Thank
you.

**Comment by yigakpoa** [comment]
@clentafrica/wg-marketing-comms this will go out on the 2nd of August @erioc

**Comment by Okpeelizabeth1989** [comment]
@ clent Africa/wg- marketing -comm.   Can we post this now

**Comment by yigakpoa** [comment]
Yes please @Okpeelizabeth1989, you will handle posting for FB & Instagram as usual, @SDauphin15 for LinkedIn, @erioc for twitter. 

Happy Friday! 🌿 Here’s a green tip to kick off your weekend: Switch to energy-efficient bulbs, like LEDs or CFLs, to significantly reduce your carbon footprint. These bulbs use up to 80% less energy than traditional incandescent bulbs and last much longer, saving you money on your energy bill while helping the environment.

Remember, small changes in our daily habits can lead to big differences in our planet’s health. Let’s all do our part for a more sustainable and eco-friendly future!

#GreenTip #EnergyEfficiency #SustainableLiving #EcoFriendly #ClimateAction #SaveEnergy #GoGreen #CLENTAfrica #GreenPractices #ClimateChange #RenewableEnergy

![Green Tip Friday - CLENT Africa](https://github.com/user-attachments/assets/a7b881db-f75f-4c75-a819-bfb5d8058d92)

**Comment by SDauphin15** [comment]
Sorry for the delay guys. I was very caught up with life and work earlier.
Sorry about that.
