### ISSUE TITLE
23rd July 2024

### ISSUE THREAD

**Issue by yigakpoa** [clentafrica/marketing-and-comms#11]
“We do not inherit the earth from our ancestors, we borrow it from our children.” – Native American Proverb. 

This powerful reminder calls us to action. Let’s take steps today to ensure a sustainable future for the next generation. Join us in making conscious choices that protect our planet and secure a healthy environment for all. 🌠🌳

 #CLENTAfrica #SustainableFuture #GreenLiving #Inspiration #EnergyEfficiency #SustainableLiving #EcoFriendly #ClimateAction #SaveEnergy #GoGreen

**Comment by yigakpoa** [comment]
Is anyone from the @clentafrica/wg-design available to work on this for the marketing team? Please indicate here. Thank you.

**Comment by SDauphin15** [comment]
Do I create a content for this caption? Please let me know. Thank you.

**Comment by yigakpoa** [comment]
Yes you can @SDauphin15 . Thank you so much

**Comment by SDauphin15** [comment]
Noted

**Comment by chibuikemezesionwu** [comment]
> Monday Motivation - “We do not inherit the earth from our ancestors, we borrow it from our children.” – Native American Proverb.
> 
> This powerful reminder calls us to action. Let’s take steps today to ensure a sustainable future for the next generation. Join us in making conscious choices that protect our planet and secure a healthy environment for all. 🌠🌳
> 
> #MondayMotivation #SustainableFuture #GreenLiving #Inspiration



> Is anyone from the @clentafrica/wg-design available to work on this for the marketing team? Please indicate here. Thank you.

I'm available

**Comment by yigakpoa** [comment]
Thank you @chibuikemezesionwu but @SDauphin15 is currently working on this. I’ll mention you on another one now.

**Comment by chibuikemezesionwu** [comment]
Alright

**Comment by yigakpoa** [comment]
Hi @SDauphin15 have you been able to work on this?

**Comment by SDauphin15** [comment]
I’m starting now. Give me until later please.

**Comment by yigakpoa** [comment]
Okay thank you @SDauphin15

**Comment by SDauphin15** [comment]
![Green Minimalist Tree of Life Logo - 3](https://github.com/user-attachments/assets/bf52b8c9-e975-40ec-9b4c-ac7c986ebfd6)
![Green Minimalist Tree of Life Logo - 3](https://github.com/user-attachments/assets/517681d6-7dfc-4445-8ae2-6602d14450de)

**Comment by SDauphin15** [comment]
Please let me know what you think

**Comment by yigakpoa** [comment]
Hi @SDauphin15 , so sorry it took this long but I finally got the chance to add a little something to your design. What do you think about it?

![Image](https://github.com/user-attachments/assets/e3fb92f1-4e88-4b0d-88e8-099ce0012cef)

**Comment by SDauphin15** [comment]
It looks good. Thank you
