### ISSUE TITLE
Plastic Free July 2 - 25th July 2024

### ISSUE THREAD

**Issue by yigakpoa** [clentafrica/marketing-and-comms#12]
At CLENT Africa, we believe that every small step can make a big difference in combating plastic pollution. In many African communities, the harmful effects of plastic waste are evident in overflowing landfills, polluted waterways, and endangered wildlife. By using reusable bags, bottles, and opting for plastic-free packaging, we can reduce the burden on our environment. Share your experiences, like using traditional African baskets instead of plastic bags, or making natural cleaning products. Together, we can educate and motivate others in our immediate community to adopt sustainable practices, helping to reduce the plastic waste that chokes our cities and countryside. 

Let’s work hand in hand to create a sustainable future, protect our beautiful landscapes, and make a lasting impact on our environment!

#PlasticFreeJuly #ReduceWaste #EcoFriendly #SustainableLiving #plasticfree #africa

**Comment by yigakpoa** [comment]
hi @chibuikemezesionwu would you like to work on this instead?

**Comment by chibuikemezesionwu** [comment]
> hi @chibuikemezesionwu would you like to work on this instead?

Sure. A poster for it?

**Comment by yigakpoa** [comment]
Yes, you can find the assets here: https://github.com/clentafrica/design/blob/main/Assets.md

**Comment by chibuikemezesionwu** [comment]
> Yes, you can find the assets here: https://github.com/clentafrica/design/blob/main/Assets.md . You can pick any part that stands out to you. It’s for an Instagram post

Alright, thank you

**Comment by chibuikemezesionwu** [comment]
Please, I have been trying to join the meeting but it's not connecting

**Comment by yigakpoa** [comment]
It's by 5pm
