### ISSUE TITLE
Q & A Saturday - 27th July 2024

### ISSUE THREAD

**Issue by yigakpoa** [clentafrica/marketing-and-comms#13]
It’s Q&A Saturday! 

Do you have questions about climate change, renewable energy, or sustainability? Drop them in the comments below, and we will provide insightful answers. Whether you’re curious about how solar panels work, the impact of wind farms, or ways to live more sustainably, we’re here to help. 

Let’s learn and grow together to make a positive impact on our planet!

#QandA #ClimateAction #SustainableAfrica #AskTheExperts #CLENTAfrica #Sustainability #GreenFuture #AfricaRising #EcoInnovation #SustainableDevelopment #ClimateAction #EnvironmentalStewardship

**Comment by yigakpoa** [comment]
Hi @clentafrica/wg-design is there anyone available to work on this?

**Comment by AyodejiOnigbogi** [comment]
> Hi @clentafrica/wg-design is there anyone available to work on this?

What's to be done?

**Comment by yigakpoa** [comment]
We’re meant to create social media graphics for this post. 1:1 dimensions

**Comment by AyodejiOnigbogi** [comment]
> We’re meant to create social media graphics for this post. 1:1 dimensions @AyodejiOnigbogi 

Noted
