### ISSUE TITLE
Poll: What Are the Biggest Environmental Challenges Your Community Faces? - 29th July 2024

### ISSUE THREAD

**Issue by yigakpoa** [clentafrica/marketing-and-comms#14]
### Poll: What Are the Biggest Environmental Challenges Your Community Faces?

We want to hear from you! What are the biggest environmental challenges your community faces? Select all that apply and share your experiences in the comments. Together, we can find effective solutions.

1. 🌊 **Plastic Pollution**
2. 🌳 **Deforestation**
3. 🚱 **Water Scarcity**
4. 🗑️ **Waste Management**
5. 🏭 **Air Pollution**
6. 🌾 **Soil Degradation**
7. 🏘️ **Urban Sprawl**

Share your thoughts and let’s collaborate to promote a healthier environment for all. 🌍🤝

#LetsTalk #CommunitySolutions #EnvironmentalChallenges #GreenAfrica

**Comment by ogbuevis** [comment]
Waste Managment

**Comment by yigakpoa** [comment]
@clentafrica/wg-design is there anyone available to work on this?

**Comment by yigakpoa** [comment]
@clentafrica/wg-design is there anyone available to work on the design for this poll?

**Comment by AyodejiOnigbogi** [comment]
> @clentafrica/wg-design is there anyone available to work on the design for this poll?

Is the whole content going into the design?

**Comment by yigakpoa** [comment]
I think that depends on the design team and if it wont be too much writeup in the design. @AyodejiOnigbogi

**Comment by AyodejiOnigbogi** [comment]
> I think that depends on the design team and if it wont be too much writeup in the design. @AyodejiOnigbogi 

Noted @clentafrica/wg-design

**Comment by Nhiddo** [comment]
@yigakpoa  I made a design on this

**Comment by AyodejiOnigbogi** [comment]
> @yigakpoa  I made a design on this 

Let's have a look

**Comment by Nhiddo** [comment]
![ClentAfrica](https://github.com/user-attachments/assets/0e6bd804-c352-43aa-af01-4583c004fb0e)
![ClentAfrica Grained](https://github.com/user-attachments/assets/ae581838-3d6b-4fa2-981f-64a824f061e6)

**Comment by yigakpoa** [comment]
Thank you @AyodejiOnigbogi, also @Nhiddo thank you for working on this! It looks unique, I love how various African flags are in the design ❤️. I would like to suggest a few things that might make it better:

- Can we replace the sentence “Empowering African communities through climate….” with the question “What are the biggest challenges…?” I think we can still leave it in capital letters?
- I think the second image with a grain effect might seem easier on the eyes since we have strong design elements in the background. I genuinely can’t tell which one I love better tbh. 
- Would it be too much if we added our linkedin? Maybe we can reduce the font size to accommodate one more social handle. 

What do you all think?

PS. next time, team mates can always share what they’ve worked on 💃

**Comment by AyodejiOnigbogi** [comment]
Just doing our jobs 😊

**Comment by Nhiddo** [comment]
@yigakpoa  I will submit the edit today. Happy new week

**Comment by Nhiddo** [comment]
@yigakpoa Here!
![ClentAfricaEnCha](https://github.com/user-attachments/assets/7a25ccca-865d-4b29-a21c-4edda8681573)

**Comment by Okpeelizabeth1989** [comment]
Ok @yigakpoa
