### ISSUE TITLE
Blogpost Social Media Post - 21st August 2024

### ISSUE THREAD

**Issue by yigakpoa** [clentafrica/marketing-and-comms#16]
In today’s blogpost (https://clentafrica.org/embracing-biodegradable-products-a-sustainable-path-for-africa/), our COO at Clent Africa shared the numerous benefits of using biodegradable products and how they can positively impact our communities in Africa:

1. **Reducing Waste:** Biodegradable products break down naturally, reducing landfill waste volume.
   
2. **Protecting Waterways:** They prevent harmful plastics from polluting rivers, lakes, and oceans, preserving aquatic life.
   
3. **Promoting Soil Health:** Biodegradable products decompose into natural substances that enrich soil, benefiting agriculture.
   
4. **Supporting Local Industries:** Choosing locally-made biodegradable products creates jobs and boosts sustainable development.
   
5. **Reducing Carbon Footprint:** These products require less energy to produce and decompose, lowering greenhouse gas emissions.
   
6. **Enhancing Public Health:** Reducing plastic pollution helps prevent the spread of toxins that can harm human health.
   
7. **Encouraging Sustainable Practices:** Adopting biodegradable products promotes environmental awareness and responsible consumption.

Stay informed by reading and sharing the full article with your network. By making these eco-friendly choices, we can safeguard our landscapes and ensure a healthier future for all. Let's build a greener Africa together! 

#SustainableSunday #Biodegradable #EcoChoices #GreenLiving #GreenAfrica #CLENTAfrica #SustainableAfrica 🌿♻️

**Comment by yigakpoa** [comment]
@clentafrica/wg-design

**Comment by AyodejiOnigbogi** [comment]
Are we to create a poster containing the above context? @yigakpoa

**Comment by yigakpoa** [comment]
Yes please @AyodejiOnigbogi. 1:1 for instagram. You can just pick any parts to highlight

**Comment by yigakpoa** [comment]
Hi @AyodejiOnigbogi https://www.canva.com/design/DAGKigFhV6g/tff6RZVWan09M9k3-V5n6Q/edit?utm_content=DAGKigFhV6g&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by AyodejiOnigbogi** [comment]
![Light Green Modern Photographic World Soil Day Instagram Post_20240725_202301_0000.png](https://github.com/user-attachments/assets/3d09fcb1-43cd-4560-8e55-e5dc950614a3)

**Comment by yigakpoa** [comment]
I love that i can see the soil & the growing plant 🌱💃. Really great work! However, i’m thinking the logo can be on the right so it’s not too much. 

I’m also thinking we need variations of this logo (like a white & black version 🤔). I don't know what @clentafrica/wg-design thinks about that. Eg if the “CLENT Africa” was orange and white, it might have been better. 

But in the meantime, can you share the link to this design, so I can do some tiny edits?

PS. I really really love this. 

Also @CharlesSodipo @chibuikemezesionwu & Uchechi are our reviewers o, I’m not a designer 🏃‍♀️😭

**Comment by AyodejiOnigbogi** [comment]
@yigakpoa 
https://www.canva.com/design/DAGL-z6SDPg/7sHeONmJAT_w-rjkuISmaQ/edit?utm_content=DAGL-z6SDPg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by yigakpoa** [comment]
![Light Green Modern Photographic World Soil Day Instagram Post (Instagram Post)](https://github.com/user-attachments/assets/1535203b-fb74-48fc-a5c1-bdc8e6ceac41)

**Comment by AyodejiOnigbogi** [comment]
> What do you think about this @AyodejiOnigbogi ?
> ![Light Green Modern Photographic World Soil Day Instagram Post (Instagram Post)](https://github.com/user-attachments/assets/1535203b-fb74-48fc-a5c1-bdc8e6ceac41)
> 

You have my  Applause 👏👏
But let's hear from @clentafrica/wg-design

**Comment by Okpeelizabeth1989** [comment]
> What do you think about this @AyodejiOnigbogi ?
> ![Light Green Modern Photographic World Soil Day Instagram Post (Instagram Post)](https://github.com/user-attachments/assets/1535203b-fb74-48fc-a5c1-bdc8e6ceac41)
> 

@yigakpoa this is beautiful

**Comment by CharlesSodipo** [comment]
Beautiful Design!
Just like Yiga said, we are allowed to change the color of the logo, to make it visible and visually appealing with choice of colors, picture and the entire design (using the brand guidelines).
This is my take.
