### ISSUE TITLE
August 1 post 

### ISSUE THREAD

**Issue by yigakpoa** [clentafrica/marketing-and-comms#22]
Welcome to August with CLENT Africa! 

Joining us in tackling climate change head-on is crucial to our journey towards a sustainable future. We can work together to unlock Africa's immense renewable energy potential so that it can sustainably power our communities. Come join us in creating a cleaner, greener Africa for generations to come. Volunteer here:

**Comment by yigakpoa** [comment]
@clentafrica/wg-design

**Comment by AyodejiOnigbogi** [comment]
> @clentafrica/wg-design 

What's needed?

**Comment by yigakpoa** [comment]
The design 💃. It can be a volunteer with us, or happy new month or a phrase from the caption; the direction is up to your creativity @AyodejiOnigbogi

**Comment by AyodejiOnigbogi** [comment]
> The design 💃. It can be a volunteer with us, or happy new month or a phrase from the caption; the direction is up to your creativity @AyodejiOnigbogi 

Noted 
I'll see as the spirit leads

**Comment by Andersonizuwa** [comment]
How do I get information on these things, I need them for web design?

   - *Our Story:* Background information about CLENT Africa and its growth.
   - *Mission & Vision:* Detailed statements about your goals and values.
   - *Team:* Profiles of key team members and their roles.
   - *Partners:* Information about our partners and collaborators.
