### ISSUE TITLE
August 12th post - IYD 2024

### ISSUE THREAD

**Issue by yigakpoa** [clentafrica/marketing-and-comms#23]
Happy International Youth Day!  This year, change makers across the globe are celebrating International Youth Day 2024 with the theme "Youth Empowerment for a Sustainable Future"! At CLENT Africa, we believe that young people are the driving force behind sustainable change. Today, we celebrate the energy, creativity, and passion of youth across the African continent but particularly, the ones at #clentafrica. Our dedicated teams in design, partnerships, disability advocacy, gender equality, community development, and more are committed to supporting and uplifting young voices who are driving change and championing sustainability. 

Youth at CLENT Africa are at the forefront of building a better world but it doesn’t end with us; share a story or tag a young leader in your community who is making a difference in sustainability, environmental conservation, technology, gender equality, or disability. 

Let's inspire others with their journey!. Join us in empowering the next generation and creating a future where everyone thrives. 

Happy International Youth Day! 🎉🙌 #IYD2024 #YouthEmpowerment #SustainableFuture #CLENTAfrica  #InternationalYouthDay #YouthPower #SustainableFuture #CLENTAfrica #YouthLeadership

——————

Design wanted 🤲🏽 @clentafrica/wg-design (I’m thinking a design with all the contributors at CLENT Africa. This is a way to celebrate our wonderful team mates. What do you think @clentafrica/wg-marketing-comms). Marketing can also do a short blogpost.

**Comment by SDauphin15** [comment]
What do you think of this design?

**Comment by yigakpoa** [comment]
Hi @SDauphin15 you forgot to upload, there’s no image

**Comment by SDauphin15** [comment]
![Uploading STREET WEAR WITH GIRL SMILE PHOTO FOR T SHIRT DESIGN.png…]()

**Comment by SDauphin15** [comment]
![STREET WEAR WITH GIRL SMILE PHOTO FOR T SHIRT DESIGN](https://github.com/user-attachments/assets/4fab4b50-d2b4-4bcc-a6e3-986f0eb724f6)

**Comment by SDauphin15** [comment]
Please let me know which one you prefer

**Comment by yigakpoa** [comment]
> ![STREET WEAR WITH GIRL SMILE PHOTO FOR T SHIRT DESIGN](https://private-user-images.githubusercontent.com/174141973/353486737-4fab4b50-d2b4-4bcc-a6e3-986f0eb724f6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNTA1OTksIm5iZiI6MTcyMjM1MDI5OSwicGF0aCI6Ii8xNzQxNDE5NzMvMzUzNDg2NzM3LTRmYWI0YjUwLWQyYjQtNGJjYy1hNmUzLTk4NmYwZWI3MjRmNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQxNDM4MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Yjc3MDgwOTM5ZDE0NzBiZjZmMmVjMGNlMzAwMWRlODc4YzdhZGU5YjIwYTQ5MGY1ZGQ5ZmQ2ZjAwNWVjNDA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yHOohxNIRA5sn2ePHeYu2knLHQhpZlphmUjlFPuzvU8)

Go Soraya! Go Soraya! @SDauphin15 This is super cute! 💃I’m thinking the image can be miniboxes containing images of actual contributors. What do you think? PS. the other one isn’t showing yet, but you ate with this one🥁.

**Comment by SDauphin15** [comment]
Thank you 😊 However, I will need photos of the contributors in order for
me to add to it. We have to send our photos. Please let me know. Thank you.

Best,
Soraya

**Comment by yigakpoa** [comment]
International Youth Day 2024

Dear Team ❤️

This year, change makers across the globe are celebrating International Youth Day 2024 with the theme "Youth Empowerment for a Sustainable Future". What better way to celebrate the bright minds at CLENT Africa than with a post shining the light on you! 

**If you would love to be a part of this**, please copy the boxed template & add your images in this [document](https://docs.google.com/document/d/17wkSu71FGXxMWk90IIPTOPKxw2t4T5vBvrDM29IuzwI/edit) with the necessary information **before** the **5th of August** to enable the marketing team to finalize the design.

Thank you so much.

@clentafrica/wg-design @clentafrica/wg-disability-gender-equality @clentafrica/wg-education @clentafrica/wg-fundraising @clentafrica/wg-marketing-comms @clentafrica/wg-energy @clentafrica/wg-partnerships @clentafrica/wg-programs  @clentafrica/wg-research-and-data

**Comment by yigakpoa** [comment]
@wg-design hellooo

**Comment by SDauphin15** [comment]
![9655a3ea-4272-4172-9be4-9ba5b068d1cb](https://github.com/user-attachments/assets/42232b45-6632-4ede-bb51-d3e6fe7adc91)

**Comment by SDauphin15** [comment]
@Okpeelizabeth1989 @Busolaodole05 please post on Twitter and Instagram
