### ISSUE TITLE
August 9th Social Media posts

### ISSUE THREAD

**Issue by erioc** [clentafrica/marketing-and-comms#25]
We do not inherit the earth from our ancestors, we borrow it from our children.” This powerful quote reminds us of our responsibility to future generations. Every action we take today impacts the world they will inherit. By committing to sustainable practices and reducing our carbon footprint, we can ensure a healthier planet for our children. Let’s pledge to make environmentally conscious choices and inspire others to do the same.
 #MondayMotivation #SustainableFuture #GreenLiving #Inspiration

@clentafrica/wg-design 

Edit …

**Comment by yigakpoa** [comment]
I will work on this 💃

**Comment by Okpeelizabeth1989** [comment]
Clentafrica/wg-design please work on this
