### ISSUE TITLE
AUG 25th - Sustainable Sunday

### ISSUE THREAD

**Issue by yigakpoa** [clentafrica/marketing-and-comms#28]
Sustainable Sunday is here to remind us of the importance of biodegradable products. These items break down naturally and reduce the burden on our landfills. By choosing biodegradable options, we can minimize our environmental impact and promote a circular economy. Small changes in our daily habits can lead to significant improvements in waste management. Let’s commit to making eco-friendly choices and inspire others to do the same.

#SustainableSunday #Biodegradable #EcoChoices #GreenLiving

**Comment by yigakpoa** [comment]
did this go out @clentafrica/wg-marketing-comms

**Comment by SDauphin15** [comment]
No it did not. There’s no design
