### ISSUE TITLE
AUG 27th - ORGANIC Farming

### ISSUE THREAD

**Issue by yigakpoa** [clentafrica/marketing-and-comms#29]
Organic farming is gaining traction across Africa, promoting healthier food and soil. This sustainable practice reduces the use of harmful chemicals and enhances biodiversity. By supporting organic farmers, we contribute to a healthier environment and food system. How does your community support sustainable agriculture? Share your stories if you have tried organic farming and let’s celebrate the benefits together.

#CLENTAfrica #OrganicFarming #SustainableAgriculture #HealthySoil

@clentafrica/wg-design

**Comment by erioc** [comment]
Yes please

**Comment by yigakpoa** [comment]
did this go out @clentafrica/wg-marketing-comms ? do we have the design yet @clentafrica/wg-design

**Comment by yigakpoa** [comment]
i think this issue was worked on by @breno02lucas in another thread. Can you please confirm @erioc

**Comment by yigakpoa** [comment]
yes it was: [here ](https://github.com/clentafrica/marketing-and-comms/issues/37). 

Closing this now. Thanks everyone 👏👏
