### ISSUE TITLE
August 26th	Climate Change and Disability: Understanding the Impact

### ISSUE THREAD

**Issue by oladipomarvel** [clentafrica/marketing-and-comms#35]
Explore how climate change disproportionately affects people with disabilities in Africa. Discuss the unique challenges they face and the importance of inclusive climate resilience strategies.

**Comment by oladipomarvel** [comment]
@clentafrica/wg-design @clentafrica/wg-marketing-comms

**Comment by SDauphin15** [comment]
Good evening, as a reminder once the design is completed, you please upload the design before Monday August 26th? Thank you @clentafrica/wg-design

**Comment by Okpeelizabeth1989** [comment]
> Let’s Talk Saturday What environmental challenges does your community face? From deforestation to water scarcity, climate change impacts us all differently. By sharing our experiences and solutions, we can support each other and find effective ways to combat these issues. At CLENT Africa, we believe in the power of community-driven change. Join the conversation and let’s work together for a sustainable future. 
>  #LetsTalk #CommunitySolutions #EnvironmentalChallenges #GreenAfrica
> 
> 
> @clentafrica/wg-design @clentafrica/wg-marketing-comms

@clentafrica/wg-design  we are still waiting for the design

**Comment by CharlesSodipo** [comment]
![Issue 35](https://github.com/user-attachments/assets/06dcc01f-17fe-409e-bb6e-7d392ed81660)
So sorry for the delay.

**Comment by yigakpoa** [comment]
I’m closing this issue since it has been worked on by @clentafrica/wg-marketing-comms & @clentafrica/wg-design. Thanks everyone
