### ISSUE TITLE
August 30th

### ISSUE THREAD

**Issue by erioc** [clentafrica/marketing-and-comms#36]
"Fun Fact Friday Did you know Africa receives an average of 325 days of sunshine a year? This makes our continent ideal for solar energy projects! Let’s harness this incredible resource to power our communities sustainably. 🌞🔋
 #FunFactFriday #SolarPower #AfricaSunshine #RenewableResources

@clentafrica/wg-design 
@clentafrica/wg-marketing-comms

**Comment by CharlesSodipo** [comment]
Will work on this and send once done

**Comment by CharlesSodipo** [comment]
![Issue 36](https://github.com/user-attachments/assets/670deaeb-f6d9-4964-97ff-ac7ab575cab7)

**Comment by erioc** [comment]
Thank you Charles
