### ISSUE TITLE
SEPTEMBER 5TH Organic Farming/Sustainable Agriculture 

### ISSUE THREAD

**Issue by erioc** [clentafrica/marketing-and-comms#37]
Organic farming is gaining traction across Africa, promoting healthier food and soil. This sustainable practice reduces the use of harmful chemicals and enhances biodiversity. By supporting organic farmers, we contribute to a healthier environment and food system. How does your community support sustainable agriculture? Share your stories and let’s celebrate the benefits of organic farming.
 #CLENTAfrica #OrganicFarming #SustainableAgriculture #HealthySoil

@clentafrica/wg-design

**Comment by breno02lucas** [comment]
Hi @erioc  !

I made the canvas on PS, but I can't send psd bcs the file size is too big.

![Post 1](https://github.com/user-attachments/assets/04219c6a-61de-4c4a-a22b-c35fce184e74)
![Post 2](https://github.com/user-attachments/assets/db2ebb00-308f-496c-87b0-4b79d75545ca)
![Post 3](https://github.com/user-attachments/assets/19c8fce8-ab0e-4ae5-a668-fcd8699324dd)

If you want any changes, just tell me!

**Comment by yigakpoa** [comment]
It’s a yes from me @breno02lucas, this looks super amazing. Thank you for working on this in such short notice.

**Comment by yigakpoa** [comment]
@SDauphin15 can we schedule this to go out on our social media platforms tomorrow?

**Comment by SDauphin15** [comment]
Ok

**Comment by SDauphin15** [comment]
@Okpeelizabeth1989 please post on fb and instagram. I will post on linkedin @erioc post on twitter please

**Comment by SDauphin15** [comment]
> @Okpeelizabeth1989 please post on fb and instagram. I will post on linkedin @erioc post on twitter please for september 5tht design
