### ISSUE TITLE
September 7th  Saturday qoute

### ISSUE THREAD

**Issue by erioc** [clentafrica/marketing-and-comms#38]
"The best time to plant a tree was 20 years ago. The second best time is now.” This Chinese proverb emphasizes the urgency of environmental action. Trees play a crucial role in absorbing carbon dioxide and providing oxygen, making them vital in our fight against climate change. By planting trees and supporting reforestation projects, we can make a lasting impact. Let’s plant seeds for a greener, healthier future.
#PlantATree #GreenerFuture #EcoWisdom

@clentafrica/wg-design

**Comment by breno02lucas** [comment]
Hey, @erioc 

I made the canvas, take a look!

**This is the Post n° 1:**

![Post 1.png](https://github.com/user-attachments/assets/499fa4ef-a940-401a-b192-66f6074e7dfa)

**This is the Post n° 2:**

![Post 2.png](https://github.com/user-attachments/assets/d55d1d1c-50c4-41e4-8c7b-6db1f9358e3e)

If u need any modifications, just let me know!

**Comment by breno02lucas** [comment]
@yigakpoa the post wasn't post on Instagram. Did we have any problems with the design?
