### ISSUE TITLE
Marketing Strategy- Axelle 

### ISSUE THREAD

**Issue by yigakpoa** [clentafrica/marketing-and-comms#41]
Hi @AxelleDongni please find attached the things you need to manage strategy for the marie team at CLENT Africa:

- READMe - https://github.com/clentafrica/marketing-and-comms
- Content calendar on Github- https://github.com/clentafrica/marketing-and-comms/tree/main/ContentCalendar/2024
- Social Media Calendar on spreadsheet- https://docs.google.com/spreadsheets/d/10ozC2-DoLrTdrMOzb8DjNlSmYqBWq9FZ3jjtXH-bZVc/edit
- To create new tasks/issues & view current ones - https://github.com/clentafrica/marketing-and-comms/issues
- Marketing Guidelines - https://docs.google.com/document/d/1WRfKtqN0nUrcRW-6g-MkMyr9aXFwv3h5cG8Jv81SpHw/edit
- Meeting Notes - https://docs.google.com/document/d/16x_d0tvJfFYVJyO0w8P1w4lvu907g6BCxktMw0l22Jk/edit

Please let me or @erioc know if you need anything

**Comment by AxelleDongni** [comment]
@yigakpoa @erioc 
I took the time to read the various documents, but I didn't see the marketing strategy for 2024. Please can you direct me to where I can get it here on GitHub?
I'm asking because I want to suggest that we start working on the 2025 strategy.

**Comment by yigakpoa** [comment]
Hi @AxelleDongni 

Thank you for taking the time to go through the documents. For the **2024 marketing strategy**, you can find the **Sketchy Content Strategy** at the following link:  https://github.com/clentafrica/marketing-and-comms/blob/main/ContentCalendar/2024/Q4-Strategy.md

I’d also suggest we schedule a meeting tomorrow, Monday, to discuss the **marketing strategy** in more detail. It would be great to have our CMOs @SDauphin15 & @erioc join as well to ensure we're all aligned as we start thinking about the **2025 strategy**.

Let me know if that works for you.
