### ISSUE TITLE
Sept 8th- International Literacy Day- Become a Climate Volunteer

### ISSUE THREAD

**Issue by yigakpoa** [clentafrica/marketing-and-comms#44]
Climate literacy is critical for the future of our planet! On this International Literacy Day, we’re highlighting the importance of educating young people about climate science and renewable energy. 🌱

 By empowering the next generation with knowledge, we equip them with the tools to lead the fight against climate change. 

Join us in promoting climate literacy across African communities by becoming a contributor to our education team here: (https://github.com/clentafrica/education/issues) ! #InternationalLiteracyDay #ClimateEducation

@clentafrica/wg-marketing-comms @clentafrica/wg-design

**Comment by SDauphin15** [comment]
Good afternoon, let me know when the design is ready. Thanks

**Comment by breno02lucas** [comment]
Hey, @SDauphin15 !

I know time is up. But, I created a canvas to call new volunteers.

![Post](https://github.com/user-attachments/assets/687ca027-4ce1-4602-83c9-7ada40737a2f)

**Comment by SDauphin15** [comment]
Thank you. It looks great.I will post this tomorrow.
