### ISSUE TITLE
Sept 10th - Technology for Climate Solutions

### ISSUE THREAD

**Issue by yigakpoa** [clentafrica/marketing-and-comms#45]
Technology is very important to revolutionize Climate Resilience in Africa!
A simple example is thats solar-powered farming can help small-scale farmers increase yields sustainably while AI-driven tools can be used predict climate shifts and help communities prepare — technology is at the heart of Africa’s fight against climate change.

At CLENT Africa, we’re working to empower communities with innovative solutions that not only protect our environment but also create new opportunities for growth and development. But we can’t do it alone! 

Your support can help us bring these technologies to more regions, ensuring every community has the tools to adapt and thrive in a changing climate.

Join us in shaping a greener, more resilient future for Africa!

#TechForGood #ClimateTech #InnovateForThePlanet #GreenAfrica #SustainableFuture #opensource 

Can anyone work on a design for this please? @clentafrica/wg-design

**Comment by breno02lucas** [comment]
Hey, @yigakpoa!

I'll work on it today for sure!

**Comment by yigakpoa** [comment]
Awesome! Thanks @breno02lucas

**Comment by breno02lucas** [comment]
Hey @yigakpoa and @SDauphin15!

Sorry if I'm late, but I fogot the timezone :( - (here is 9pm).

Follow the canvas above: 

**CANVA 1**

![Post 1](https://github.com/user-attachments/assets/2e2c3312-299c-4fe4-bec6-5279f0795904)

**CANVA 2**

![Post 2](https://github.com/user-attachments/assets/9ef5b0fe-8c42-4492-b58f-633556093c9e)

**CANVA 3**

![Post 3](https://github.com/user-attachments/assets/7efe515c-5692-46b2-b46a-92dff2b0c664)

**CANVA 4**

![Post 4](https://github.com/user-attachments/assets/96c4d799-0a73-4b56-9497-0839a7036817)

**Comment by SDauphin15** [comment]
@erioc since design is ready you could post on twitter. I will post on Linkedin. I am really not sure who will post on IG. I can if you give me access. Thanks

**Comment by erioc** [comment]
Hello @breno02lucas thanks for the design but I think we should avoid pasting everything 
In the caption in he design. The caption is basically a guide for your design but in this case you have pasted everything on  different designs. I don't know if you get my point

**Comment by breno02lucas** [comment]
Hi, @erioc  !

I got your point, but as @yigakpoa said, I was trying to make a carousel of those information as I did with another one. 
I'll use different design styles for each post/publication and use information based on the caption as you asked, and don't just paste everything into a post from now on.

Thanks for the guidance!
