### ISSUE TITLE
Sept 15th - World Cleanup Day

### ISSUE THREAD

**Issue by yigakpoa** [clentafrica/marketing-and-comms#46]
It's World Cleanup Day! 

Time to roll up our sleeves and take action for a cleaner planet. Whether it's picking up litter in your community or participating in recycling programs, every small effort makes a big difference. 

Let’s unite to keep our environment clean and protect Africa’s natural beauty for future generations. 

What will you do to help today? 

#WorldCleanupDay #KeepAfricaClean #Volunteer #Climatechange

**Comment by breno02lucas** [comment]
@yigakpoa, you can assign it to me, I'll work on it!

**Comment by yigakpoa** [comment]
Done, thanks @breno02lucas

**Comment by breno02lucas** [comment]
Sending the canva <3

![Post](https://github.com/user-attachments/assets/be154625-3d93-486f-bd91-80103edc9230)

**Comment by yigakpoa** [comment]
This looks great to me @breno02lucas . Thank you so much. 

Over to @clentafrica/wg-marketing-comms for scheduling. CC @erioc & @SDauphin15

**Comment by yigakpoa** [comment]
This didn’t go out @clentafrica/wg-marketing-comms !! 😳😳

**Comment by Okpeelizabeth1989** [comment]
> This didn’t go out @clentafrica/wg-marketing-comms !! 😳😳 
> 

Can we post it now

**Comment by yigakpoa** [comment]
No please, it’s not even right that we forgot because it’s so important to
the work we do. I’m guessing this happened because we didn’t organize an
actual program around it.

But that’s fine. We’re just 2 months+ old babies as an organization so we
shouldn’t be too hard on ourselves ❤️.
