### ISSUE TITLE
Sept 16th - International Day for the Preservation of the Ozone Layer

### ISSUE THREAD

**Issue by yigakpoa** [clentafrica/marketing-and-comms#48]
The ozone layer is our planet’s natural shield, protecting all life from harmful UV rays. Today, on World Ozone Day, we celebrate the incredible progress made in its recovery — a true testament to the power of global cooperation. 

But the journey isn’t over yet! To safeguard the ozone layer and tackle the broader challenges of climate change, we must continue to reduce emissions and embrace renewable energy. Every step we take toward sustainability helps protect not just our atmosphere, but the health of our planet and future generations. 

The fight isn’t over. Let’s act now to ensure a cleaner, healthier world for all. Together, we can continue building a climate-resilient future! 

#OzoneDay #ClimateActionNow #ProtectThePlanet #RenewableEnergy #ForFutureGenerations

Cc _ @clentafrica/wg-design

**Comment by breno02lucas** [comment]
@yigakpoa  can you assign it to me!

**Comment by yigakpoa** [comment]
Thank you. Done @breno02lucas , please assign or mention @erioc & @SDauphin15 when you’re done.

**Comment by breno02lucas** [comment]
I'm sending the narration script. I separated the caption into a line to make the video, so when it is posted we could use a catchphrase as a caption, for exemple: "Protect the ozone, protect our future!" and the hashtags.

[Voiceover Script.docx](https://github.com/user-attachments/files/16982173/Voiceover.Script.docx)

If you want to change anything, just tell me!

**Comment by SDauphin15** [comment]
Hey Breno,

I’m sorry. I got so busy Since I’m going away. Please have someone else do
it. I can’t do it right now. I’ll be back next Wednesday. Thank you.

Best,
Soraya

**Comment by yigakpoa** [comment]
Hi @erioc please were you able to voice out this reel for @breno02lucas ? It’s meant to go out today?

**Comment by breno02lucas** [comment]
Good morning, @yigakpoa 

I didn't receive the voiceover and yesterday was a busy day at university, work and stuffs. I couldn't work at Clent because I didn't have time to.

I am so, so sorry!

**Comment by yigakpoa** [comment]
Oh @breno02lucas , good morning ! That's fine, I absolutely understand. Please take all the time you need whenever you need to work on stuff at the university. 

Again our teams are just under 3 months and we’re doing really great so far. All we need to do is find ways to make sure we learn from operational processes and collaborate better. 

FWIW you are one of our best contributors already and you’ve only just begun, so Thank You!

**Comment by breno02lucas** [comment]
> Hey @breno02lucas did you get the voiceover ?

Hii, no :/
