### ISSUE TITLE
Sept 23	- International Day of Sign Languages - Become a Volunteer

### ISSUE THREAD

**Issue by yigakpoa** [clentafrica/marketing-and-comms#49]
On this International Day of Sign Languages, let’s talk about #climateaccessibility! 🤟

At CLENT Africa, we believe that everyone — including the Deaf and hard-of-hearing community — deserves equal access to critical climate information and solutions. Our Disability and Gender Equality Team is working tirelessly to break down barriers, ensuring that climate knowledge reaches all corners of society.

Whether it’s through sign language videos explaining renewable energy, or accessible workshops on climate adaptation and resilience, we’re committed to making sure that no one is left behind in the fight against climate change. 

But we can’t do it alone. We need passionate individuals like you to help us expand this mission of inclusion and accessibility. By volunteering with CLENT Africa, you can be part of creating innovative solutions, like:

	• Producing climate-related content in sign languages for diverse audiences.
	• Hosting inclusive climate workshops that ensure participation from persons with disabilities.
	• Advocating for policies that promote gender equality and accessibility in climate action.

Join us in making climate action accessible to all! Sign up today to volunteer and be part of a movement that’s changing the world — one inclusive solution at a time. https://forms.gle/FR2A4fja8jfW2HLRA

Together, we can create a future where everyone has the tools to fight climate change and thrive. 

#SignLanguagesDay #InclusionInClimate #ClimateAccessibility #TechforGood #VolunteerWithCLENTAfrica #EqualityForAll #AccessibleClimateAction

Cc @clentafrica/wg-design @clentafrica/wg-marketing-comms

**Comment by yigakpoa** [comment]
@clentafrica/wg-design any updates on the design for this?

**Comment by breno02lucas** [comment]
> @clentafrica/wg-design any updates on the design for this?

Yes, here:

![Post](https://github.com/user-attachments/assets/68d80141-ee23-440d-b597-dc1de51ef5ff)

**Comment by yigakpoa** [comment]
Okay. i’ll  take a look at it.

**Comment by SDauphin15** [comment]
Loooks good. It’s scheduled on LinkedIn!

**Comment by erioc** [comment]
Nice, scheduled for on Twitter

**Comment by Okpeelizabeth1989** [comment]
> > @clentafrica/wg-design any updates on the design for this?
> 
> Yes, here:
> 
> ![Post](https://github.com/user-attachments/assets/68d80141-ee23-440d-b597-dc1de51ef5ff)
> 

@clentafrica/wg-design  nice
