### ISSUE TITLE
Renewable Energy post - 12th July

### ISSUE THREAD

**Issue by yigakpoa** [clentafrica/marketing-and-comms#5]
CAPTION:

Did you know that Africa holds immense potential for renewable energy? 🌞 From the vast deserts perfect for solar farms to the strong coastal winds ideal for wind turbines, the continent is rich in natural resources that can drive a sustainable energy future.

At CLENT Africa, we are committed to harnessing this potential. By leveraging cutting-edge technology and innovative solutions, we aim to provide clean, reliable, and affordable energy to communities across Africa. Our projects focus on not only reducing carbon footprints but also empowering local communities through job creation and sustainable development.

Together, we can power Africa’s future sustainably! Join us in embracing clean energy and making a positive impact on our planet by contributing here: https://forms.gle/FTUDSLNrwPzZauw6A.

**Comment by yigakpoa** [comment]
Waiting on design assets. If you would like to take this up, please leave a comment - @Okpeelizabeth1989 @SDauphin15 @Busolaodole05

**Comment by yigakpoa** [comment]
Hi @SDauphin15 please can you reshare the design here so we can post it?

**Comment by Busolaodole05** [comment]
Should I post it on Linkedln now?

**Comment by SDauphin15** [comment]
![Clear Africa](https://github.com/user-attachments/assets/fb1877ca-59d4-4648-9951-368d727972bb)

**Comment by yigakpoa** [comment]
Yes please @Busolaodole05 @Okpeelizabeth1989 please let’s schedule this 💃. Thank You so much. 

Thank you too to Soraya @SDauphin15 👏

**Comment by yigakpoa** [comment]
This has now been posted on all our platforms, so i’m closing it. Thanks team
