### ISSUE TITLE
Sept 26th - Global Day of Climate Action

### ISSUE THREAD

**Issue by yigakpoa** [clentafrica/marketing-and-comms#50]
Today is the Global Day of Climate Action — and we need YOUR voice more than ever! 

Africa is on the frontlines of the climate crisis. From severe droughts in the Sahel to flooding in coastal cities, the continent is facing some of the most devastating impacts of climate change — despite contributing the least to the problem. But we also have an incredible opportunity to lead in climate resilience and sustainable solutions. 

Whether it’s signing petitions, reducing your carbon footprint, or demanding stronger climate policies from leaders, every action matters. African communities are already stepping up, but we need global solidarity and bold action to protect our future.

What will YOU do to fight climate change today? Your voice, your actions, and your commitment can help create a future where African nations are resilient and thriving, despite the challenges we face.

The planet needs us — especially those most affected, like communities across Africa. Together, we have the power to reshape the future and build a world where everyone can thrive. Let’s make this the turning point! 

#GlobalClimateAction #ActForClimate #AfricaForClimate #SaveOurPlanet #ClimateJusticeNow #OurFutureOurFight

Cc @clentafrica/wg-design @clentafrica/wg-marketing-comms

**Comment by yigakpoa** [comment]
@clentafrica/wg-design is anyone available to work on this?

**Comment by SDauphin15** [comment]
Still waiting on design.
