### ISSUE TITLE
Sept 29- World Heart Day

### ISSUE THREAD

**Issue by yigakpoa** [clentafrica/marketing-and-comms#51]
Did you know that climate change is threatening public health — especially in Africa’s most vulnerable communities?

As temperatures rise and air pollution worsens, it’s not just the planet that suffers — it’s our people. In Africa, women, children, and the elderly are often hit hardest by these challenges. From heatwaves to droughts, from polluted air to food insecurity, climate change deepens poverty and makes it even harder for families to stay healthy.

On this World Heart Day our Chief Health Officer - Dr. Barile Ikpae, encourages us to remember that protecting the planet also means protecting our hearts and our communities. Poor families, already struggling to survive, face the double burden of health issues linked to a warming climate. Children suffer from asthma due to pollution. The elderly, who are already vulnerable, are at greater risk from heat-related illnesses. And women, who are often caregivers, bear the emotional and physical toll of supporting their families in a rapidly changing environment.

We cannot turn a blind eye. Together, we must act now to build a healthier, greener future where everyone can thrive — regardless of their circumstances.

💚 A healthy planet means healthier people. Let’s fight for both.

#WorldHeartDay #ClimateAndHealth #HealthyPlanetHealthyPeople #ClimateJustice #FightForOurFuture  #worldheartday2024 #environmentalhealth #environmentalhealthandsafety 

Cc @clentafrica/wg-marketing-comms @clentafrica/wg-design

**Comment by SDauphin15** [comment]
@clentafrica/wg-design please start working on this design. Thank you🙏🏾

**Comment by Okpeelizabeth1989** [comment]
>  Did you know that climate change is threatening public health — especially in Africa’s most vulnerable communities?
> 
> As temperatures rise and air pollution worsens, it’s not just the planet that suffers — it’s our people. In Africa, women, children, and the elderly are often hit hardest by these challenges. From heatwaves to droughts, from polluted air to food insecurity, climate change deepens poverty and makes it even harder for families to stay healthy.
> 
> On this World Heart Day, let’s remember that protecting the planet also means protecting our hearts and our communities. Poor families, already struggling to survive, face the double burden of health issues linked to a warming climate. Children suffer from asthma due to pollution. The elderly, who are already vulnerable, are at greater risk from heat-related illnesses. And women, who are often caregivers, bear the emotional and physical toll of supporting their families in a rapidly changing environment.
> 
> We cannot turn a blind eye. Together, we must act now to build a healthier, greener future where everyone can thrive — regardless of their circumstances.
> 
> 💚 A healthy planet means healthier people. Let’s fight for both.
> 
> #WorldHeartDay #ClimateAndHealth #HealthyPlanetHealthyPeople #ClimateJustice #FightForOurFuture
> 
> Cc @clentafrica/wg-marketing-comms @clentafrica/wg-design 

@yigakpoa nice one

**Comment by SDauphin15** [comment]
Awaiting on the design. Thank you

**Comment by WrEck3rr09** [comment]
Hello. I am a new member and do not know how to operate github. Can you
please brief me as to what I have to work on. Sorry, it is confusing.
Thanks!

**Comment by breno02lucas** [comment]
@erioc @SDauphin15 @yigakpoa  , sending the design below:

![World Heart Day](https://github.com/user-attachments/assets/5d16c782-dcdc-4027-ae5e-299435dcfeb9)

**Comment by SDauphin15** [comment]
Thank you @breno02lucas . Nice Design!

@Okpeelizabeth1989 or @yigakpoa  please post on IG&FB . @erioc please post on twitter. I scheduled the post on LinkedIn. It’s due tomorrow 09/29

**Comment by yigakpoa** [comment]
Done for FB, IG & Twitter
