### ISSUE TITLE
24th September - Join Us for Hacktoberfest 2024 - 

### ISSUE THREAD

**Issue by yigakpoa** [clentafrica/marketing-and-comms#53]
**🌍 Join CLENT Africa for Hacktoberfest 2024!**

We’re calling on all **developers, no-code enthusiasts, and community builders** to contribute to CLENT Africa this Hacktoberfest! Hacktoberfest is here, and we want **YOU** to help drive sustainable development across Africa by contributing to our open-source projects across **Environmental Health**, **Climate Education**, **Disability Advocacy**, and **Gender Equality**. 🌱

Whether you code or not, there’s a team for you to make an impact! Here’s how you can contribute:

💻 **Code Contributions**:
- **Health Tech**: Develop solutions to improve health outcomes through environmental monitoring and education.
- **Backend** : Build systems that power data-driven projects for climate education and gender equality.
- **Frontend** : Enhance our user interfaces to improve #accessibility for users with #disabilities.
  
📝 **No-Code Contributions**:
- **Documentation**: Proofread and enhance our documentation to make our projects more user-friendly.
- **User Testing**: Review and test demos, ensuring accessibility and inclusivity for all.
- **Content Creation**: Help develop educational content on environmental health, climate, and gender advocacy.
- **Accessibility Testing**: Help ensure our website and web-based applications can be used by people with disabilities.

✨ **Teams You Can Join**:
- **Environmental Health**: Work on tech projects improving health outcomes by addressing climate-related challenges.
- **Climate Education**: Help create digital tools to teach and engage communities about climate action.
- **Disability & Gender Equality**: Build platforms that promote accessibility and #equality across the continent.
- **Research & Data**: Data analysis for climate impact and sustainable solutions.
- **Marketing & Communications**: Help us spread the word by contributing to our content and outreach efforts.
- **Community Engagement**: Assist in managing our growing community and onboarding new contributors.
- **Design**: Create user friendly designs for our community. 

🔗 Repositories to Explore:
- [CLENT Africa GitHub](https://github.com/orgs/clentafrica/repositories)

Join us this #Hacktoberfest2024 and contribute to meaningful change! Together, we can build a more #sustainable and equitable future. 🌍

#OpenSource #Hacktoberfest #CLENTAfrica #HealthTech #Sustainability #a11y #communitymanagement #data #analytics #genderequality #ClimateAction #GenderEquality #ContributeNow #opensourcesoftware

@clentafrica/wg-design is anyone available to work on a simple design to call on contributors for Hacktoberfest 2024?

**Comment by erioc** [comment]
No one worked on this? @clentafrica/wg-design ?

**Comment by yigakpoa** [comment]
Hi team @clentafrica/wg-design & @clentafrica/wg-marketing-comms 

Please find a design here: 

<img width="600" alt="CLENT Africa X Hacktoberfest 2024" src="https://github.com/user-attachments/assets/b38bef6b-80aa-4107-ad5f-02d4696fc3e0">

**Comment by yigakpoa** [comment]
Posted on all our platforms 💃
