### ISSUE TITLE
OCT 11 - International Day of the Girl: Celebrating Girls’ Vision for the Future

### ISSUE THREAD

**Issue by yigakpoa** [clentafrica/marketing-and-comms#55]
At CLENT Africa, we are proud to work alongside incredible women who are leading the charge against climate change and shaping the future of sustainability across Africa. This year’s theme, ‘Girls’ Vision for the Future,’ highlights the power and impact of young female leaders committed to building a greener, more inclusive world.

Here are some of the amazing women driving our mission forward:
- **Research and Data Team**: Leading efforts to gather and analyze vital climate data to inform impactful solutions.
- **People Operations (People Ops)**: Ensuring our teams are empowered, supported, and aligned with CLENT Africa’s goals.
- **Marketing Team**: Spreading the message of climate action and engaging communities in the fight against climate change.
- **Disability and Gender Equality Team**: Advocating for accessible and inclusive climate solutions for all, ensuring that women and people with disabilities are not left behind.
- **Environmental Health Team**: Addressing the intersection of climate change and health, developing strategies that protect and uplift vulnerable communities.

Today, we celebrate these women and all girls who envision a sustainable, equitable future for our planet. Your leadership and passion are making a lasting impact.

Join us in amplifying their voices and supporting their work. Together, we can create a future where every girl’s vision becomes a reality.

**Dear Girl Child, your future is powerful, and CLENT Africa stands with you!**

#InternationalDayOfTheGirl #WomenInClimate #GirlsLeadTheChange #ClimateAction #EmpowerGirls #SustainableFuture #CLENTAfrica #GirlsForClimate

**Comment by yigakpoa** [comment]
@clentafrica/wg-design anybody available to work on this?

**Comment by EmmanetD** [comment]
Hi team,

Can we quickly work on this as we only have tomorrow to finalize everything?

Can the team leads of @clentafrica/wg-research-and-data, @clentafrica/wg-disability-gender-equality, @clentafrica/wg-health, @clentafrica/wg-hr  @clentafrica/wg-design, @clentafrica/wg-design ,@clentafrica/wg-marketing-comms nominate a female member from their respective teams for us to highlight and celebrate? Kindly send the name and picture. The deadline for sharing the details is 12 pm tomorrow.

@clentafrica/wg-design, who is available to assist us with the design work?

@clentafrica/wg-programs @clentafrica/wg-community-managers

**Comment by JosephRay01** [comment]
Hello
I’m here to help you with your project
Let me know the project you have to do
And I’ll let you know how we will go about it ok…

**Comment by EmmanetD** [comment]
Hi @JosephRay01 , we need to create designs (carousel)  to showcase the nominated individuals from each team. The idea is to highlight the women at CLENT Africa who have been doing great work while celebrating the International Day of The Girl Child. Are we good to go?

**Comment by JosephRay01** [comment]
Alright that’s cool it’s what I can help you with
I’ll need some details from you and can I know your budget on this design
so we can work around it

**Comment by EmmanetD** [comment]
😃 @JosephRay01 , Our team is building with open source. We all dedicate our free time to contribute collaboratively towards projects. Your support in this regard is greatly appreciated. , 🙏🏻 🎉

**Comment by JosephRay01** [comment]
Alright so what are you saying about the project now

**Comment by EmmanetD** [comment]
Are you available to volunteer and help out with the designs?

**Comment by EmmanetD** [comment]
Dear Team Leads, To make the submission easy, kindly rename the picture using this format: [nominee's name]_[team of nominee], then upload it to this folder: https://drive.google.com/drive/folders/1NlVADIieBZsZfPE9Rpj2mR-0lDxec9Uy . Thank you!

**Comment by Rayccheal** [comment]
This is a beautiful idea! I have a question, though. Since we are nominating people, how about we go ahead and nominate them, and then the nominated individuals can send in their pictures? The truth is (my thoughts), we hardly have pictures of each other, so having the nominees send in their pictures could make the process easier. Or, is there a better way you think we can go about this?

**Comment by EmmanetD** [comment]
Hi @Rayccheal , that's fine. However, it's important that the nominated members submit their pictures using the specified format. They can upload them to the folder I shared.
