### ISSUE TITLE
Urgent Action For A Safer Future! 18th October 

### ISSUE THREAD

**Issue by erioc** [clentafrica/marketing-and-comms#56]
"We must secure the safest possible future for people and the planet. That means taking urgent action"

Antonio Guterres
UN Secretary General

Caption
Our planet's future hinges on the actions we take today. Let's commit to reducing emissions, safeguarding communities from climate extremes, increasing climate finance, and holding the fossil fuel industry accountable. Together, we can secure a safer future for all. 

#ClimateActionNow 
#SaveOurPlanet  
#FossilFreeFuture  
#ActOnClimate

P.S the text in bold is meant to be on the poster.

@clentafrica/wg-design please assign someone this issue. Thank you

**Comment by breno02lucas** [comment]
Hey @erioc, 
It's hereeee

![Post](https://github.com/user-attachments/assets/820c52a9-d34b-442a-b56e-148055f2df74)

**Comment by erioc** [comment]
@SDauphin15 and @yigakpoa please schedule this post for tomorrow. Thank you

**Comment by yigakpoa** [comment]
Scheduled for FB & Instagram
