### ISSUE TITLE
Carousel 21st October 

### ISSUE THREAD

**Issue by erioc** [clentafrica/marketing-and-comms#57]
Slide 1: Title slide: What are you doing about climate change?

Slide 2 :  Reducing my carbon footprint.

Slide 3: Supporting renewable energy.

Slide 4: Minimizing waste.

Slide 5:  Planting trees

Slide 6: Educating & spreading awareness

**Caption** 

Climate change affects all of us, and we all have a part to play. 🌍 So, what are you doing about it? From reducing your carbon footprint to advocating for policy changes, every action matters. Let us know in the comments—how are you contributing to a more sustainable future? 💬👇 Together, we can make a difference!

#ClimateActionNow #ActOnClimate #SustainableLiving #ProtectOurPlanet

@clentafrica/wg-design

**Comment by breno02lucas** [comment]
Hello, @erioc 

Follow the carousel below:
![1](https://github.com/user-attachments/assets/649424a4-35ab-44f4-8ee2-e352f4d5a32a)
![2](https://github.com/user-attachments/assets/746d5836-73b4-47ca-9e39-e01f26803632)
![3](https://github.com/user-attachments/assets/d38e6832-869c-4a0c-a8fd-cd63703aea4d)
![4](https://github.com/user-attachments/assets/d2dab258-bec2-42a1-ad8b-e4e901981698)
![5](https://github.com/user-attachments/assets/9aebd364-1b8a-4c7d-a258-6a01d5c50674)
![6](https://github.com/user-attachments/assets/ea0f791e-bc02-44b5-9f6c-3500b062ac88)

**Comment by erioc** [comment]
Thank you Breno

**Comment by erioc** [comment]
Hello @SDauphin15 and @yigakpoa please schedule this post for Monday. I'll be posting twitter.

**Comment by erioc** [comment]
Reminder to most this today @yigakpoa
