### ISSUE TITLE
Plastic Free July - 14th July Post

### ISSUE THREAD

**Issue by yigakpoa** [clentafrica/marketing-and-comms#7]
This Plastic Free July, we challenge you to reduce your plastic use. Single-use plastics are a major environmental concern, contributing to pollution and harming wildlife. By opting for reusable alternatives, we can make a significant impact. 
Share your tips for living a plastic-free life and inspire others to join the movement. Together, we can create a cleaner, healthier planet.

#ClentAfrica #PlasticFreeJuly #ReduceWaste #EcoFriendly #SustainableLiving

**Comment by yigakpoa** [comment]
<img width="540" alt="Green Illustration Say No To Plastic Campaign Instagram Post" src="https://github.com/user-attachments/assets/8c77c2f0-f5b2-4094-9b42-9648dca9b564">

**Comment by SDauphin15** [comment]
I like this illustration

**Comment by Okpeelizabeth1989** [comment]
Nice design

**Comment by yigakpoa** [comment]
@Okpeelizabeth1989 please post this on FB & Instagram while @SDauphin15 posts on LinkedIn. I will post on twitter for now.  

——
This Plastic Free July, we challenge you to reduce your plastic use. Single-use plastics are a major environmental concern, contributing to pollution and harming wildlife. By opting for reusable alternatives, we can make a significant impact.
Share your tips for living a plastic-free life and inspire others to join the movement. Together, we can create a cleaner, healthier planet.

#ClentAfrica #PlasticFreeJuly #ReduceWaste #EcoFriendly #SustainableLiving



![Image](https://github.com/user-attachments/assets/3dd68dd9-baa0-4cd3-b1b5-62ef08c1811f)

**Comment by yigakpoa** [comment]
Done for twitter 💃

**Comment by SDauphin15** [comment]
Noted. I will post now

**Comment by Okpeelizabeth1989** [comment]
Posted this since on the 14th on Facebook and Instagram
